version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: potato
      POSTGRES_PASSWORD: potato_password
      POSTGRES_DB: potato_projects
    ports:
      - '5433:5432'
    volumes:
      - potato_pgdata:/var/lib/postgresql/data

volumes:
  potato_pgdata:
